sudo: required

language: php

services:
  - docker

env:
  global:
    - SIMPLETEST_DB=mysql://drupal:drupal@db/drupal
    - SIMPLETEST_BASE_URL="http://web:80"

before_install:
  # Build all containers before installing
  - docker-compose build

install:
  # Install Composer managed dependencies
  - docker-compose run php-cli composer --verbose install

before_script:
  # Start the web container
  - docker-compose up -d web

script:
  - curl -I localhost
  - docker-compose run php-cli composer run-script --timeout=0 tests
  - docker-compose run -w /var/www/html/web php-cli drush site-install --verbose --yes
  - docker-compose run -w /var/www/html/web php-cli drush status
  - docker-compose run -w /var/www/html/web php-cli drupal site:status

