FROM drupaldocker/php:7-cli

ARG USER_UID=1000

# Install needed CLI tools (for Drush)
RUN apt-get update && apt-get install -y mysql-client openssh-client rsync \
  && mkdir -p /etc/drush \
  && echo "<?php \$options['root'] = '/var/www/html/web';" > /etc/drush/drushrc.php \
  && rm -rf /var/lib/apt/lists/*

# Create the runtime user account
RUN useradd --uid ${USER_UID} --create-home php
USER ${USER_UID}